django:
  restart: always
  build: ./django/
  expose: 
    - "8000"
  links:
    - postgres:postgres
  env_file: .env
  volumes:
    - ./django:/user/src/app:ro

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - django
  links:
    - django:django

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  expose:
    - "5432"
  env_file: ./postgres/.env
