django:
  restart: always
  build: ./django/
  ports:
    - "8001:8001"
  expose: 
    - "8000"
  links:
    - postgres:postgres
  env_file: .env
  volumes:
    - ./django:/user/src/app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - django
  links:
    - django:django

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - ./:/backup
  expose:
    - "5432"
  env_file: ./postgres/.env